vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    ticket_file:
      uri_prefix: /uploads
      upload_destination: "%kernel.project_dir%/public/uploads" # directory where uploaded files should be stored
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_remove: true # default true, it means the file should be deleted when the entity is removed
      delete_on_update: true # default true, it means the file should be deleted when a new file is uploaded
      inject_on_load: false # default false, it means the file should be injected into the uploadable entity when it is loaded from the data store. The object will be an instance of Symfony\Component\HttpFoundation\File\File.

